server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: medicase-backend
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/medicase
      auto-index-creation: true
  
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  
  security:
    user:
      name: admin
      password: admin123
  
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:medicase-super-secret-key-for-jwt-tokens-2024}
  expiration: 86400000 # 24 hours in milliseconds
  refresh-expiration: 604800000 # 7 days in milliseconds

# File Upload Configuration
file:
  upload:
    max-size: 50MB
    allowed-types: 
      - application/pdf
      - image/jpeg
      - image/png
      - image/gif
      - application/msword
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document

# CORS Configuration
cors:
  allowed-origins: 
    - http://localhost:4200
    - http://localhost:3000
  allowed-methods: 
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Logging Configuration
logging:
  level:
    com.medicase: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Application Specific Configuration
app:
  qr:
    base-url: ${QR_BASE_URL:http://localhost:4200/patient}
    image-format: PNG
    image-size: 200
  
  pagination:
    default-page-size: 20
    max-page-size: 100