server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: medicase-backend
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/medicase
      auto-index-creation: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  
  security:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# JWT Configuration
jwt:
  secret: medicase-secret-key-change-in-production
  expiration: 86400000 # 24 hours in milliseconds

# File Upload Configuration
file:
  upload-dir: ./uploads
  max-size: 10485760 # 10MB

# QR Code Configuration
qr:
  size: 300
  base-url: http://localhost:4200/patient

# Logging
logging:
  level:
    com.medicase: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/medicase.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always